language: node_js
node_js:
  - 5
sudo: false
cache:
  directories:
  - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    packages:
    - g++-4.8
install:
  - npm install
  - webpack --config ./webpack-production.config.js --progress --colors


