olanguage: node_js
node_js:
  - "5"
sudo: false
cache:
  directories:
  - node_modules
before_install:
  - npm install
  - webpack --config ./webpack-production.config.js --progress --colors
idnstall:
  - npm install

